service: cp3405
org: hungnguy
app: cp3405

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: default

plugins:
  - serverless-offline
  
functions:
  authenticate_test:
    handler: handler.authenticate_test
    events:
     - http:
         path: authenticate_test
         method: post
         cors: true
  wd_groups:
    handler: handler.cp3405
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: POST
          path: /authenticate
          cors: true
      - http:
          method: POST
          path: /transfertest
          cors: true
      - http: 
          method: POST
          path: /sendmail
          cors: true
      - http:
          method: POST
          path: /transfer_byqrtest
          cors: true
      - http:
          method: POST
          path: /transfer
          cors: true