service: cp3405
org: zwenyantoe
app: myapp

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: default

plugins:
  - serverless-offline
  
functions:
  wd_groups:
    handler: handler.cp3405
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: POST
          path: /authenticate
          cors: true
      - http:
          method: POST
          path: /transfer
          cors: true
      - http: 
          method: POST
          path: /sendmail
          cors: true
      - http:
          method: POST
          path: /transfer_byqr
          cors: true
