# service: cp3405
# org: hungnguy
# app: cp3405

service: cp3405
org: zwenyantoe
app: myapp

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: default

plugins:
  - serverless-offline
  
functions:
  authenticate_test:
    handler: handler.authenticate
    events:
     - http:
         path: authenticate
         method: post
         cors: true
  transfer:
    handler: handler.transfer
    events:
     - http:
         path: transfer
         method: post
         cors: true
  save_transaction:
    handler: handler.save_transaction
    events:
     - http:
         path: save_transaction
         method: post
         cors: true
  sendmail:
    handler: handler.sendmail
    events:
     - http:
         path: sendmail
         method: post
         cors: true
  sendinvoice:
    handler: handler.sendinvoice
    events:
      - http:
          path: sendinvoice
          method: post
          cors: true
  get_otp:
    handler: handler.get_otp
    events:
      - http:
          path: get_otp
          method: post
          cors: true
  check_otp:
    handler: handler.check_otp
    events:
      - http:
          path: check_otp
          method: post
          cors: true
  wd_groups:
    handler: handler.cp3405
    events:
      - http:
          method: GET
          path: /
          cors: true