service: cp3405
org: hungnguy
app: cp3405

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: cp3405

plugins:
  - serverless-offline
  
functions:
  wd_groups:
    handler: handler.cp3405
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: POST
          path: /authenticate
          cors: true
      - http:
          method: POST
          path: /transfer
          cors: true
      

